<Project>
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<ItemGroup>
		<PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
		<PackageVersion Include="NUnit" Version="4.5.1" />
		<PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
		<PackageVersion Include="Portable.BouncyCastle" Version="1.9.0" />
		<PackageVersion Include="System.Resources.Extensions" Version="10.0.5" />
	</ItemGroup>

	<ItemGroup>
		<PackageVersion Include="WSCT.Core" Version="6.7.1" />
		<PackageVersion Include="WSCT.Helpers" Version="5.2.0" />
		<PackageVersion Include="WSCT.GUI" Version="6.2.1" />
		<PackageVersion Include="WSCT.GUI.Plugins" Version="5.2.1" />
		<PackageVersion Include="WSCT.GUI.Plugins.LayerInteractive" Version="3.2.1" />
		<PackageVersion Include="WSCT.GUI.Resources" Version="1.2.1" />
		<PackageVersion Include="WSCT.Plugin.ISO7816Tools" Version="5.2.3" />
		<PackageVersion Include="WSCT.Wrapper.Desktop" Version="1.5.0" />
	</ItemGroup>
</Project>