using System;
using System.Text;

using WSCT.Helpers;

namespace WSCT.EMV.Security
{
    /// <summary>
    /// Represents an EMV Data Authentication (Data Format: 05).
    /// </summary>
    /// <remarks>Format used for DDA and CDA.</remarks>
    public abstract class AbstractDataAuthenticationFormat05 : AbstractSignatureContainer
    {
        #region >> Fields

        private Byte[] _iccDynamicData;

        private Byte[] _padPattern;

        #endregion

        #region >> Properties

        /// <summary>
        /// ICC Dynamic Data Length: Identifies the length of the ICC Dynamic Data in bytes.
        /// </summary>
        public Byte IccDynamicDataLength
        {
            get { return _recovered[3]; }
        }

        /// <summary>
        /// ICC Dynamic Data (LDD):  Dynamic data generated by and/or stored in the ICC.
        /// </summary>
        public Byte[] IccDynamicData
        {
            get
            {
                if (_iccDynamicData == null)
                {
                    _iccDynamicData = new Byte[IccDynamicDataLength];
                    Array.Copy(_recovered, 4, _iccDynamicData, 0, IccDynamicDataLength);
                }
                return _iccDynamicData;
            }
        }

        /// <summary>
        /// Pad Pattern (NIC - LDD - 25): (NIC - LDD - 25) padding bytes of value 'BB'.
        /// </summary>
        public Byte[] PadPattern
        {
            get
            {
                if (_padPattern == null)
                {
                    _padPattern = new Byte[KeyLength - IccDynamicDataLength - 25 - 1];
                    Array.Copy(_recovered, 5 + IccDynamicDataLength, _padPattern, 0, KeyLength - IccDynamicDataLength - 25 - 1);
                }
                return _padPattern;
            }
        }

        #endregion

        #region >> Constructors

        /// <summary>
        /// Initializes a new <see cref="AbstractDataAuthenticationFormat05"/> instance.
        /// </summary>
        protected AbstractDataAuthenticationFormat05()
            : base(2)
        {
        }

        #endregion

        #region >> Object

        /// <inheritdoc />
        public override string ToString()
        {
            var s = new StringBuilder();
            s.AppendFormat("Header:[{0:X2}] ", DataHeader);
            s.AppendFormat("Format:[{0:X2}] ", DataFormat);
            s.AppendFormat("Hash Algorithm:[{0:X2}] ", HashAlgorithmIndicator);
            s.AppendFormat("ICC Dynamic Data Length:[{0:X2}] ", IccDynamicDataLength);
            s.AppendFormat("ICC Dynamic Data:[{0}] ", IccDynamicData.toHexa('\0'));
            s.AppendFormat("Pad:[{0}] ", PadPattern.toHexa('\0'));
            s.AppendFormat("Hash:[{0}] ", HashResult.toHexa('\0'));
            s.AppendFormat("Trailer:[{0:X2}] ", DataTrailer);

            return s.ToString();
        }

        #endregion
    }
}
