<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Version>1.2.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>wsct-emvrsa</AssemblyName>
		<RootNamespace>WSCT.EMV.IccCertificateGenerationConsole</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<OutputPath>..\binaries</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EMV Library\EMV Library.csproj" />
	</ItemGroup>
</Project>