<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Version>3.2.1</Version>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.EMV.ConsoleTests</PackageId>
		<Description>Test Console of EMV Library for WSCT.</Description>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>WSCT.EMV.ConsoleTests</AssemblyName>
		<RootNamespace>WSCT.EMV.ConsoleTests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.Wrapper.Desktop" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EMV Library\EMV Library.csproj" />
	</ItemGroup>
</Project>