<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<Version>3.3.2</Version>
	</PropertyGroup>

	<PropertyGroup>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>WSCT.GUI.Plugins.EMVExplorer</PackageId>
		<Description>EMV Explorer Plugin for WinSCard GUI.</Description>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>Plugins.EMVExplorer</AssemblyName>
		<RootNamespace>WSCT.GUI.Plugins.EMVExplorer</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="WSCT.GUI" />
		<PackageReference Include="WSCT.GUI.Resources" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\EMV Library\EMV Library.csproj" />
	</ItemGroup>
	
	<ItemGroup>
		<Content Include="Config.EMVExplorer.xml">
			<Visible>True</Visible>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Pack>True</Pack>
			<PackageCopyToOutput>True</PackageCopyToOutput>
		</Content>
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Gui.cs" />
		<Compile Update="Gui.Designer.cs" SubType="Form" DependentUpon="Gui.cs" />
	</ItemGroup>
	<ItemGroup>
		<Compile Update="Resources\Lang.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Lang.resx</DependentUpon>
		</Compile>
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Update="Resources\Lang.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Lang.Designer.cs</LastGenOutput>
		</EmbeddedResource>
	</ItemGroup>
</Project>