<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<Version>1.2.0</Version>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyName>wsct-emvicc</AssemblyName>
		<RootNamespace>WSCT.EMV.IccCertificateGenerationConsole</RootNamespace>
	</PropertyGroup>

	<PropertyGroup>
		<OutputPath>..\binaries</OutputPath>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\EMV Library\EMV Library.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="icc-certificate-data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="issuer-certificate-data.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>